services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend-static:/app/static
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always

volumes:
  backend-static:
